services:
  gazebo:
    build: .
    stop_signal: SIGINT
    environment:
      - DISPLAY
      - ROS_DOMAIN_ID
      - SDF_FILE=ur3e_world.sdf
      - CONTAINER_SDF_PATH=/root/gazebo/sdf
    privileged: true # Needed for some gpu configurations.
    volumes:
      - ../:/root/gazebo/ # Share base repository folder with container
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
      - ../../sas_robot_driver_gazebo:/root/sas_robot_driver_gazebo_devel/src/sas_robot_driver_gazebo
    command: /bin/bash -c "
      export GZ_SIM_RESOURCE_PATH=$$GZ_SIM_RESOURCE_PATH:/root/gazebo
      && cd "$$CONTAINER_SDF_PATH"
      && (gz sim "$$SDF_FILE" &)
      && cd /root/sas_robot_driver_gazebo_devel
      && ls .
      && colcon build
      && source install/setup.bash
      && gz topic -l
      && gz service -l
      && (ros2 launch sas_robot_driver_gazebo robot_driver_server_launch.py &)
      && ros2 launch sas_robot_driver_gazebo server_launch.py"
